# Set theme
remote_theme: daviddarnes/alembic@main
#theme: alembic-jekyll-theme
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://rtcsa2023.github.io'
#baseurl: ''
title: 'IEEE RTCSA'
#description: 'The 29th IEEE International Conference on Embedded and Real-Time Computing Systems and Applications'
nvmsa2023: 'https://rtcsa2023.github.io'
permalink: pretty

#logo:

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: CFP
  url: /cfp/
- title: Program
  url: /comingsoon/
- title: Submissions
  url: '/index#submissions'
- title: Venue
  url: '/index#venue'
- title: Registration
  url: '/index#registration'
- title: Visa
  url: '/index#visa'
- title: RTCSA2022
  url: https://rtcsa.org/index.html
- title: NVMSA2023
#  url: {nvmsa2023}

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"




# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
